services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: elysia
      POSTGRES_USER: elysia
      POSTGRES_PASSWORD: elysia
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
